---
- name: building the docker images
  hosts: node2
  become: true 
  tasks:



    - name: pull the docker image from docker hub
      docker_image:
        name: mysql
        source: pull
        state: present

    - name: remove the present image
      docker_image:
        name: mysql
        state: absent

    - name: run the MySQL image 
      docker_container:
        name: myhtp
        image: httpd
        state: started  
        restart_policy: always  
        ports:
          - "7070:80"
        env:
          HTTPD__DocumentRoot: /var/www/public
          HTTPD__ServerAdmin: webmaster@example.org
          HTTPD__AddDefaultCharset: UTF-8
          HTTPD_a2enmod: rewrite status expires
         
    - name: install webserver
      docker_container:
        name: webserver
        image: tomee
        state: started
        ports:
          - "6060:8080"
